queue_rules:
  - name: default
    conditions:
      - check-success=fmt
      - check-success=clippy
      - check-success=test
    merge_method: rebase

pull_request_rules:
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
