queue_rules:
  - name: default
    conditions:
      - check-success=Format
      - check-success=Clippy
      - check-success=Test
    merge_method: rebase

pull_request_rules:
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
